export const SERVICE_CATEGORIES = [
    { value: "barber", label: "Barber" },
    { value: "braiding", label: "Braiding" },
    { value: "electronics", label: "Electronics" },
    { value: "makeup", label: "Makeup" },
    { value: "nails", label: "Nails" },
    { value: "housing", label: "Housing" },
    { value: "automobile", label: "Automobile" },
    { value: "photography", label: "Photography" },
    { value: "tailoring", label: "Tailoring" },
    { value: "cooking", label: "Cooking" },
    { value: "massage", label: "Massage" },
    { value: "cleaning", label: "Cleaning" },
    { value: "graphic-design", label: "Graphic Design" },
    { value: "music", label: "Music" },
    { value: "tutoring", label: "Tutoring" },
    { value: "note-taking", label: "Note Taking" },
    { value: "essay-writing", label: "Essay Writing" },
    { value: "research-assistance", label: "Research Assistance" },
    { value: "programming-help", label: "Programming Help" },
  ];


export const PRODUCT_CATEGORIES = [
    "electronics",
    "clothing",
    "fashion",
    "auto",
    "food",
    "outdoor",
    "entertainment",
    "home",
    "baby",
    "health",
    "beauty",
    "sports",
    "pet",
    "art",
    "musical",
    "toys",
    "gaming",
    "office",
    "school",
    "books",
    "appliances",
    "housewares",
    "furniture",
    "bedding",
    "decor",
    "cookware",
    "kitchen",
    "bath",
    "storage",
    "luggage",
    "handbags",
    "shoes",
    "clothing",
    "accessories",
    "jewelry",
    "watches",
    "eyewear",
    "fitness",
    "wellness",
    "pharmacy",
    "cosmetics",
    "skincare",
    "haircare",
    "makeup",
    "nails",
    "sneakers",
    "men's wear",
    "women's wear",
    "kid's wear",
    "gadgets"
]


export const PRODUCT_BRANDS = [
  { name: "Apple", categories: ["electronics", "smartphones"] },
  { name: "Google", categories: ["electronics", "smartphones", "computers"] },
  { name: "Microsoft", categories: ["electronics", "computers", "gaming"] },
  { name: "Amazon", categories: ["electronics", "computers", "smart home"] },
  { name: "Facebook", categories: ["electronics", "smartphones", "computers"] },
  { name: "Asus", categories: ["electronics", "computers"] },
  { name: "Lenovo", categories: ["electronics", "computers"] },
  { name: "HP", categories: ["electronics", "computers"] },
  { name: "Dell", categories: ["electronics", "computers"] },
  { name: "Intel", categories: ["electronics", "computers"] },
  { name: "Nvidia", categories: ["electronics", "computers", "gaming"] },
  { name: "AMD", categories: ["electronics", "computers"] },
  { name: "Sony", categories: ["electronics", "computers", "gaming", "audio"] },
  { name: "Samsung", categories: ["electronics", "smartphones", "computers", "smart home"] },
  { name: "LG", categories: ["electronics", "smartphones", "computers", "smart home"] },
  { name: "Huawei", categories: ["electronics", "smartphones", "computers"] },
  { name: "OnePlus", categories: ["electronics", "smartphones", "computers"] },
  { name: "Xiaomi", categories: ["electronics", "smartphones", "computers", "smart home"] },
  { name: "Oppo", categories: ["electronics", "smartphones", "computers"] },
  { name: "Vivo", categories: ["electronics", "smartphones", "computers"] },
  { name: "Realme", categories: ["electronics", "smartphones", "computers"] },
  { name: "Poco", categories: ["electronics", "smartphones", "computers"] },
  { name: "Motorola", categories: ["electronics", "smartphones", "computers"] },
  { name: "Nokia", categories: ["electronics", "smartphones", "computers"] },
  { name: "HTC", categories: ["electronics", "smartphones", "computers"] },
  { name: "Acer", categories: ["electronics", "computers"] },
  { name: "MSI", categories: ["electronics", "computers", "gaming"] },
  { name: "Razer", categories: ["electronics", "computers", "gaming"] },
  { name: "Corsair", categories: ["electronics", "computers", "gaming"] },
  { name: "HyperX", categories: ["electronics", "computers", "gaming"] },
  { name: "SteelSeries", categories: ["electronics", "computers", "gaming"] },
  { name: "Logitech", categories: ["electronics", "computers"] },
  { name: "ViewSonic", categories: ["electronics", "computers"] },
  { name: "Epson", categories: ["electronics", "computers"] },
  { name: "Canon", categories: ["electronics", "computers"] },
  { name: "Brother", categories: ["electronics", "computers"] },
  { name: "Lexmark", categories: ["electronics", "computers"] },
  { name: "HP Printer", categories: ["electronics", "computers"] },
  { name: "Gucci", categories: ["fashion", "men's clothing"] },
  { name: "Prada", categories: ["fashion", "women's clothing"] },
  { name: "Chanel", categories: ["fashion", "women's clothing", "perfume"] },
  { name: "Dior", categories: ["fashion", "women's clothing", "perfume"] },
  { name: "Hermes", categories: ["fashion", "luxury", "handbag"] },
  { name: "Louis Vuitton", categories: ["fashion", "luxury", "handbag"] },
  { name: "Chlo ", categories: ["fashion", "women's clothing", "shoes"] },
  { name: "Dolce & Gabbana", categories: ["fashion", "women's clothing", "perfume"] },
  { name: "Versace", categories: ["fashion", "women's clothing", "perfume"] },
  { name: "Burberry", categories: ["fashion", "winter clothes", "outerwear"] },
  { name: "Calvin Klein", categories: ["fashion", "men's clothing", "underwear"] },
  { name: "Ralph Lauren", categories: ["fashion", "men's clothing", "polo"] },
  { name: "Tommy Hilfiger", categories: ["fashion", "men's clothing", "denim"] },
]