export const serviceCategories = [
    { value: "barber", label: "Barber" },
    { value: "braiding", label: "Braiding" },
    { value: "electronics", label: "Electronics" },
    { value: "makeup", label: "Makeup" },
    { value: "nails", label: "Nails" },
    { value: "housing", label: "Housing" },
    { value: "automobile", label: "Automobile" },
    { value: "photography", label: "Photography" },
    { value: "tailoring", label: "Tailoring" },
    { value: "cooking", label: "Cooking" },
    { value: "massage", label: "Massage" },
    { value: "cleaning", label: "Cleaning" },
    { value: "graphic-design", label: "Graphic Design" },
    { value: "music", label: "Music" },
    { value: "tutoring", label: "Tutoring" },
    { value: "note-taking", label: "Note Taking" },
    { value: "essay-writing", label: "Essay Writing" },
    { value: "research-assistance", label: "Research Assistance" },
    { value: "programming-help", label: "Programming Help" },
  ];


export const productCategories = [
    { value: "apple", label: "Apple", category: "electronics" },
    { value: "google", label: "Google", category: "electronics" },
    { value: "microsoft", label: "Microsoft", category: "electronics" },
    { value: "amazon", label: "Amazon", category: "electronics" },
    { value: "facebook", label: "Facebook", category: "electronics" },
    { value: "asus", label: "Asus", category: "electronics" },
    { value: "lenovo", label: "Lenovo", category: "electronics" },
    { value: "hp", label: "HP", category: "electronics" },
    { value: "dell", label: "Dell", category: "electronics" },
    { value: "intel", label: "Intel", category: "electronics" },
    { value: "nvidia", label: "Nvidia", category: "electronics" },
    { value: "amd", label: "AMD", category: "electronics" },
    { value: "sony", label: "Sony", category: "electronics" },
    { value: "samsung", label: "Samsung", category: "electronics" },
    { value: "lg", label: "LG", category: "electronics" },
    { value: "huawei", label: "Huawei", category: "electronics" },
    { value: "oneplus", label: "OnePlus", category: "electronics" },
    { value: "xiaomi", label: "Xiaomi", category: "electronics" },
    { value: "oppo", label: "Oppo", category: "electronics" },
    { value: "vivo", label: "Vivo", category: "electronics" },
    { value: "realme", label: "Realme", category: "electronics" },
    { value: "poco", label: "Poco", category: "electronics" },
    { value: "google-pixel", label: "Google Pixel", category: "electronics" },
    { value: "motorola", label: "Motorola", category: "electronics" },
    { value: "nokia", label: "Nokia", category: "electronics" },
    { value: "htc", label: "HTC", category: "electronics" },
    { value: "acer", label: "Acer", category: "electronics" },
    { value: "msi", label: "MSI", category: "electronics" },
    { value: "razer", label: "Razer", category: "electronics" },
    { value: "corsair", label: "Corsair", category: "electronics" },
    { value: "hyperx", label: "HyperX", category: "electronics" },
    { value: "steelseries", label: "SteelSeries", category: "electronics" },
    { value: "logitech", label: "Logitech", category: "electronics" },
    { value: "viewsonic", label: "ViewSonic", category: "electronics" },
    { value: "epson", label: "Epson", category: "electronics" },
    { value: "canon", label: "Canon", category: "electronics" },
    { value: "brother", label: "Brother", category: "electronics" },
    { value: "lexmark", label: "Lexmark", category: "electronics" },
    { value: "hp-printer", label: "HP Printer", category: "electronics" },
    { value: "gucci", label: "Gucci", category: "fashion" },
    { value: "prada", label: "Prada", category: "fashion" },
    { value: "chanel", label: "Chanel", category: "fashion" },
    { value: "dior", label: "Dior", category: "fashion" },
    { value: "louis-vuitton", label: "Louis Vuitton", category: "fashion" },
    { value: "hugo-boss", label: "Hugo Boss", category: "fashion" },
    { value: "calvin-klein", label: "Calvin Klein", category: "fashion" },
    { value: "ralph-lauren", label: "Ralph Lauren", category: "fashion" },
    { value: "abercrombie-&-fitch", label: "Abercrombie & Fitch", category: "fashion" },
    { value: "north-face", label: "North Face", category: "fashion" },
    { value: "patagonia", label: "Patagonia", category: "fashion" },
    { value: "uniqlo", label: "Uniqlo", category: "fashion" },
    { value: "zara", label: "Zara", category: "fashion" },
    { value: "h&m", label: "H&M", category: "fashion" },
    { value: "gap", label: "Gap", category: "fashion" },
    { value: "levis", label: "Levis", category: "fashion" },
    { value: "nike", label: "Nike", category: "fashion" },
    { value: "adidas", label: "Adidas", category: "fashion" },
    { value: "reebok", label: "Reebok", category: "fashion" },
    { value: "converse", label: "Converse", category: "fashion" },
    { value: "audi", label: "Audi", category: "auto" },
    { value: "bmw", label: "BMW", category: "auto" },
    { value: "mercedes-benz", label: "Mercedes-Benz", category: "auto" },
    { value: "volkswagen", label: "Volkswagen", category: "auto" },
    { value: "toyota", label: "Toyota", category: "auto" },
    { value: "lexus", label: "Lexus", category: "auto" },
    { value: "ford", label: "Ford", category: "auto" },
    { value: "chevrolet", label: "Chevrolet", category: "auto" },
    { value: "jeep", label: "Jeep", category: "auto" },
    { value: "hyundai", label: "Hyundai", category: "auto" },
    { value: "kia", label: "Kia", category: "auto" },
    { value: "food", label: "Food", category: "food" },
    { value: "beverage", label: "Beverage", category: "food" },
    { value: "snack", label: "Snack", category: "food" },
    { value: "camping-gear", label: "Camping Gear", category: "outdoor" },
    { value: "fitness", label: "Fitness", category: "outdoor" },
    { value: "outdoor", label: "Outdoor", category: "outdoor" },
    { value: "musical-instrument", label: "Musical Instrument", category: "entertainment" },
    { value: "furniture", label: "Furniture", category: "home" },
    { value: "electronic-device", label: "Electronic Device", category: "electronics" },
    { value: "book", label: "Book", category: "entertainment" },
    { value: "clothing", label: "Clothing", category: "fashion" },
    { value: "accessory", label: "Accessory", category: "fashion" },
    { value: "bike", label: "Bike", category: "outdoor" },
    { value: "car-part", label: "Car Part", category: "auto" },
    { value: "sport-equipment", label: "Sport Equipment", category: "outdoor" },
    { value: "art", label: "Art", category: "entertainment" },
    { value: "collectible", label: "Collectible", category: "entertainment" },
    { value: "baby-product", label: "Baby Product", category: "baby" },
    { value: "toys", label: "Toys", category: "entertainment" },
]
