

export const SuieLocations: string[] = [
    "Rendleman Hall",
    "Founders Hall", 
    "Alumni Hall",
    "Peck Hall",
    "Lovejoy Library", 
    "Dunham Hall",
    "Science Buildings East and West",
    "Morris University Center",
    "Art and Design",
    "Art and Design West",
    "Center for Spirituality and Sustainability",
    "Metcalf Student Experimental Theater",
    "Student Fitness Center", 
    "First Community Arena at the Vadalabene Center",
    "Early Childhood Center",
    "Cougar Village Commons", 
    "Supporting Services / University Police",
    "Woodland Residence Hall",
    "Prairie Residence Hall", 
    "Engineering Building",
    "B. Barnard Birger Hall",
    "Bluff Residence Hall",
    "Museum Operations", 
    "200 University Park",
    "100 North Research Dr.",
    "95 North Research Drive", 
    "Chamber of Commerce",
    "School of Pharmacy Lab",
    "National Corn-to-Ethanol Research Center", 
    "Ralph Korte Stadium",
    "Environmental Resources Training Center", 
    "Technology and Management Center",
    "Stratton Quadrangle", 
    "Evergreen Residence Hall",
    "47 North Research Dr.", 
    "110 North Research Dr.",
    "Biotechnology Laboratory", 
    "Incubator",
    "Dental Clinic",
    "Library Storage Facility", 
    "Swimming Pool",
    "Heating & Refrigeration Plant", 
    "Outdoor Recreational Sports Complex",
    "SIUE Credit Union", 
    "Shaw Sky Lab",
    "Student Success Center", 
    "Physics Observatory",
    "Fulginiti Indoor Softball", 
    "Simmons Law Firm",
    "Baseball Complex", 
    "The Gardens Support Center",
    "The \"e\" Sculpture"
];

